version: '3.6'
services:
  traefik:
    hostname: traefik
    image: traefik:latest
    container_name: traefik
    restart: always
    domainname: mydomain.com
    networks:
      - traefik_proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:traefik.mydomain.com"
      - "traefik.frontend.whiteList.sourceRange=192.168.1.0/24,2001:db8:dead:beef::/64" # Optional
      - "traefik.frontend.whiteList.useXForwardedFor=true"                              # Optional
      - "traefik.port=8080"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.auth.basic=${HTTP_USERNAME}:${HTTP_PASSWORD}"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${DOMAINNAME1}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik


  seafile:
    labels:
      - "traefik.enable=true"
      - "traefik.seafapp.backend=Seafile Web App"
      - "traefik.seafapp.frontend.rule=Host:seafile.mydomain.com"
      - "traefik.seafapp.port=8000"
      - "traefik.seafdav.backend=Seafile WebDAV Server"
      - "traefik.seafdav.frontend.rule=Host:seafile.mydomain.com;PathPrefixStrip:/seafdav"
      - "traefik.seafdav.port=8080"
      - "treafik.seafhttp.backend=Seafile File Server"
      - "traefik.seafhttp.frontend.rule=Host:seafile.mydomain.com;PathPrefixStrip:/seafhttp"
      - "traefik.seafhttp.port=8082"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=mydomain.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
